### ISSUE TITLE
Role is null in FailedAssert

### ISSUE THREAD

**Issue by nikola-krstic-nortal** [itplr-kosit/validator#101]
For asserts which are type of "WARN" FailedAssertRoleType value is null.
Example of used schematron assert: 
`<assert id="BR-BT-00505-0022" role="WARN" diagnostics="BT-505-Organization-Company" test="count(cbc:WebsiteURI) &gt; 0 or not(cac:PartyName/cbc:Name)">rule|message|BR-BT-00505-0022</assert> ` . 
More samples available in https://github.com/OP-TED/eForms-SDK/blob/1.0.0/schematrons/static/validation-stage-2a.sch.

I am also attaching debug screenshot for more clarifications:
![sample](https://user-images.githubusercontent.com/98452534/199677982-51ad6665-0b4f-4349-bc70-2edf9992d67c.png)

**Comment by apenski** [comment]
@rkottmann is this a bug within the validator, or is this related to the schematron rules provded by xrechnung?

**Comment by rkottmann** [comment]
as stated above it seems to be an error in the Validator API.  The Schemtron example above is valid schematron.

**Comment by apenski** [comment]
the API basically returns the content of the schematron output (svrl). It's just a reading via JAXB and return from the object. Seems to me, as if there is no "role" in the output. Can you confirm this?

**Comment by nikola-krstic-nortal** [comment]
Role is available, just not named as same as in svrl-kosit.xsd where it is "warning" and we have "WARN". Also, we have cases where one schematron has "error" and other one "ERROR" , therefore use of xsd will not work again. Why don't 'role' is not exposed as plain string?

**Comment by rkottmann** [comment]
> @rkottmann What's your opinion on that?

To relax it to xs:string^.

thx for fixing

**Comment by apenski** [comment]
Well, then I'll do that. Wasn't sure about implications in e.g. xrechnung. I'll schedule this for the next minor release (targeted for december)

**Comment by rkottmann** [comment]
It is fully backwards compatible because it just relaxes requirements
