### ISSUE TITLE
BR-17 BT-59 Same name für Payee and Seller is an error since xrechnung-2.3

### ISSUE THREAD

**Issue by aronkankel** [itplr-kosit/validator#113]
Since xrechnung-validator 1.5.0 with schematron 1.8.1 the BR-17 check reports an error, if seller name and payee name are identically.

    <ram:ApplicableHeaderTradeAgreement>
      <ram:BuyerReference>123456XRechnung</ram:BuyerReference>
      <ram:SellerTradeParty>
        <ram:Name>Beispieldaten</ram:Name>
        <ram:DefinedTradeContact>

    <ram:ApplicableHeaderTradeSettlement>
      <ram:InvoiceCurrencyCode>EUR</ram:InvoiceCurrencyCode>
      <ram:PayeeTradeParty>
        <ram:Name>Beispieldaten</ram:Name>
      </ram:PayeeTradeParty>

XML + Report are in the ZIP:
[BR-17.zip](https://github.com/itplr-kosit/validator/files/11158065/BR-17.zip)

With xrechnung-validator 1.4.2 with schematron 1.7.3 no error is reported.

The rule BR-17 didn't changed since xrechnung-1.1.
"BR-17 Eine Rechnung (INVOICE) muss den Namen des Zahlungsempfän-
gers "Payee name" (BT-59) enthalten, wenn sich der Zahlungsemp-
fänger "PAYEE" (BG-10) vom Verkäufer "SELLER" (BG-4) unterscheidet."

The Business-Term BT-59 says, the name can be equal.
"Payee name BT-59 Text 1 20
Der Name des Zahlungsempfängers.
Anmerkung: Wird verwendet, wenn der Zahlungsempfänger nicht mit dem Verkäufer identisch ist. Gleichwohl
kann der Name des Zahlungsempfänger identisch sein mit dem Namen des Verkäufers."

Is it a bug in the validator/schematron?

**Comment by aronkankel** [comment]
Î think, I found the reason.
BR-17 is not a xrechnung-rule, it's a CII-rule.
Because of an error in path of that rule, the rule never checked correct.

Here's the issue:
https://github.com/ConnectingEurope/eInvoicing-EN16931/issues/322

Here's the correction (Oktober 2022):
https://github.com/ConnectingEurope/eInvoicing-EN16931/commit/a7cda0afcde3607aca44313c4d3bc8dc9417b6be

I'll close the issue here.

**Comment by bdewein** [comment]
Thanks for reporting!
As you said, the changed behaviour is caused by the fix of BR-17 in CII, now revealing the conflict between BR-17 check and BT-59 description. We will file an issue at CEN. 
Should this be an actual use case for you (identical Payee name (BT-59) and Seller name (BT-27) in case of different Seller (BG-4) and Payee (BG-10)), please contact us at xrechnung@finanzen.bremen.de for a possible workaround until CEN issue is solved.

**Comment by aronkankel** [comment]
@bdewein Thanks for your reply. The description of BG-10 (Payee) says, only fill BG-10 if the payee differs from the seller.
So it's easy for me to omit the section, because in our app it's not possible to set another payee.
