### ISSUE TITLE
[BR-CO-15]- D16B SCRDM (Subset) CII uncoupled - ram:TaxTotalAmount benötigt currencyID

### ISSUE THREAD

**Issue by ultradr3mer** [itplr-kosit/validator#12]
Die Prüfung 
>   <xsl:when test="(ram:GrandTotalAmount = round(     ram:TaxBasisTotalAmount*100 + ram:TaxTotalAmount[@currencyID=/rsm:CrossIndustryInvoice/rsm:SupplyChainTradeTransaction/ram:ApplicableHeaderTradeSettlement/ram:InvoiceCurrencyCode]*100 +0)      div 100) or     ((ram:GrandTotalAmount = ram:TaxBasisTotalAmount) and not (ram:TaxTotalAmount[@currencyID=/rsm:CrossIndustryInvoice/rsm:SupplyChainTradeTransaction/ram:ApplicableHeaderTradeSettlement/ram:InvoiceCurrencyCode]))"/>

> [BR-CO-15]-Invoice total amount with VAT (BT-112) = Invoice total amount without VAT (BT-109) + Invoice total VAT amount (BT-110).

Macht es notwendig, dass die currencyID in TaxTotalAmount der SpecifiedTradeSettlementHeaderMonetarySummation angegeben wird. Ist das wirklich gewünscht? scheinbar ist das die einzige Stelle bei der eine currencyID erforderlich ist. An anderen Stellen ist das untersagt.

**Comment by rkottmann** [comment]
Hi, diese Frage gehört nicht hier hin. Da der Validator ein allgemeines Validierungstool aller mögliche XML Schema und Schematron ist. Diese Frage findet am meisten Fachpublikum zur richtigen Beantwortung in https://github.com/CenPC434/validation/issues . Dort muesste die Frage jedoch auf Englisch gestellt werden.
