### ISSUE TITLE
ValidationTool 1.5.0 Fails with "java.lang.IllegalArgumentException: No repository location for scenario definition 'default_1'"

### ISSUE THREAD

**Issue by horstoeko** [itplr-kosit/validator#120]
Hi,

after moving from 1.4.0 to 1.5.0 I get an error when calling the validator

```java.lang.IllegalArgumentException: No repository location for scenario definition 'default_1'```

I call the validator in this form

```java -jar "./validationtool-1.5.0-standalone.jar" -s "./scenarios.xml" "./xrechnung.xml"```

Do you have any idea what this could be?

Regards.

**Comment by msccip** [comment]
Hi,
with 1.5.0 you have to specify the -r(epository) option with the path where the validation files are stored.

**Comment by horstoeko** [comment]
Hi,

much thanks for your help. I tried that and it fixed by "problem".

Regards
