### ISSUE TITLE
Force use of Oracle JDK xml implementation

### ISSUE THREAD

**Issue by rkottmann** [itplr-kosit/validator#13]
- [ ] Make explicit in Documentation

- [ ]  and in code somehow like this example:

```
log.info("Force usage of oracle xml implementation");
// DOM-Implementation
System.setProperty("org.w3c.dom.DOMImplementationSourceList",
"com.sun.org.apache.xerces.internal.dom.DOMXSImplementationSourceImpl");
// SchemaFactory
System.setProperty(SchemaFactory.class.getName() + ":" + XMLConstants.W3C_XML_SCHEMA_NS_URI,
"com.sun.org.apache.xerces.internal.jaxp.validation.XMLSchemaFactory");
// DocumentBuilderFactory
System.setProperty(DocumentBuilderFactory.class.getName(), "com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderFactoryImpl");
// TransformerFactory
System.setProperty(TransformerFactory.class.getName(), "com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl");
```

**Comment by christian-schlichtherle** [comment]
Would this create a problem for downstream dependencies?

For example, the KoSIT validator is a dependency of our code and it’s dependent on Saxon HE. We use Saxon HE because we have XSLT 3 transformations.

We are directly `new`ing the `Processor` class from the Saxon HE API, but I would like to double check.

**Comment by apenski** [comment]
well, this ticket was created when we used JDK xml stack for xml processing. However, we moved to saxon s9api internally for all xml processing since this is way more efficient in memory usage. So this ticket is not relevant anymore. 

And thus, no problems for downstream dependencies 😄
