### ISSUE TITLE
Esablish test for using validator and validator configuration within a jar lib

### ISSUE THREAD

**Issue by rkottmann** [itplr-kosit/validator#15]
There is sometimes the use case that third parties want to include validator and a configuration with in there application and package both as a jar.

For several reasons, we do not support this well, yet. However, it is a useful feature.

**Comment by apenski** [comment]
relates to #28

**Comment by apenski** [comment]
There are tests now for this in the correspondung unit tests. See [ContentRepositoryTest](https://github.com/itplr-kosit/validator/blob/master/src/test/java/de/kosit/validationtool/impl/ContentRepositoryTest.java) and [ScenarioRepositoryTest](https://github.com/itplr-kosit/validator/blob/master/src/test/java/de/kosit/validationtool/impl/ScenarioRepositoryTest.java)
