### ISSUE TITLE
Make XML Security Level customizable

### ISSUE THREAD

**Issue by rkottmann** [itplr-kosit/validator#16]
Currently, validator has a strict XML security policy and only allows loading XML Schema from local file resources.

Some users want a less strict security policy in their runtime context. Therefore, I consider this a useful feature.

**Comment by rkottmann** [comment]
This is also a prerequisite for issue  #15

**Comment by apenski** [comment]
xml security (loading) ist configurable via API now. See [API documentation] (https://github.com/itplr-kosit/validator/blob/master/docs/api.md) for details
