### ISSUE TITLE
Consider validating the use of specific file encodings 

### ISSUE THREAD

**Issue by rkottmann** [itplr-kosit/validator#18]
Standards like XRechnung want to be able to check for the file encoding of XML files. Consider implementing this is as an optional/customizable feature which can be configured in scenarios.xml and or via CLI flags.

**Comment by fbuettner-hb** [comment]
What should be checked, exactly? 

- The presence of the encoding declaration `encoding="UTF-8"` in the XML prolog?
- Whether the document is actually valid UTF-8 (i.e., it uses only valid code point encodings)?
- Both?

In general, the encoding declaration is optional (cf. https://www.w3.org/TR/xml/#dt-xmldecl).
