### ISSUE TITLE
Creating the report seems to use too way much memory - DOMDestination to blame?

### ISSUE THREAD

**Issue by fbuettner-hb** [itplr-kosit/validator#20]
Class de.kosit.validationtool.impl.tasks.CreateReportAction uses a DOMDestination instead of the built in Saxon tree model. Same holds for input and output for de.kosit.validationtool.cmd.ExtractHtmlContentAction.

**Comment by rkottmann** [comment]
If one disables writing original document into the rpeort output then the memorz consumption is significantly less

**Comment by apenski** [comment]
* Internal processing uses saxon only now
* [Check](https://github.com/itplr-kosit/validator/blob/master/src/main/java/de/kosit/validationtool/api/Check.java) extended with 2 method that return XdmNode
* API-compatibility kept (the methods which return w3c-Document return a read-only view now)

**Comment by rkottmann** [comment]
>     * API-compatibility kept (the methods which return w3c-Document return a read-only view now)

that`s why slanted for a minor release now

**Comment by apenski** [comment]
this is implemented and will be shipped with the next release
