### ISSUE TITLE
Allow for java only configuration for standard validations such as xRechnung

### ISSUE THREAD

**Issue by JannickWeisshaupt** [itplr-kosit/validator#33]
At the moment a validation scenario must be configured via a scenario.xml file together with a multiple xsl and other configuration files. However most users of this library would probably prefer if everything they need would be included in a jar file and could be configured via the java api. I would propose something like this as the first possibility to set up a scenario (in addition to the old style via a scenario.xml):

        CheckConfiguration config = new CheckConfiguration(DefaultScenarios.xRechnung);
        Check validator = new DefaultCheck(config);

This should essentially be equal to the validator-configuration-xrechnung repository. 
If one needs more flexibility something like this should be included as the second possibility:
        
        Scenario scenario = new Scenario();
        scenario.setValidators(DefaultValidator.xRechnungCII, DefaultValidator.xRechnungUBL, Validator.fromXsl(somePath))
        scenario.setReport(DefaultReport.xRechnung)
        // or 
        scenario.setReport(Report.fromXsd(someOtherPath))

        CheckConfiguration config = new CheckConfiguration(scenario);
        Check validator = new DefaultCheck(config);

**Comment by rkottmann** [comment]
Thx! This is intersting suggestion. We will have a look at this.

**Comment by apenski** [comment]
Fixed with release [1.3.0](https://github.com/itplr-kosit/validator/releases/tag/v1.3.0) 
See [API documentation](https://github.com/itplr-kosit/validator/blob/v1.3.0/docs/api.md) for details
