### ISSUE TITLE
Be able to read PDF files

### ISSUE THREAD

**Issue by jstaerk** [itplr-kosit/validator#38]
In order to be able to validate ZUGFeRD 2 and Factur-X against the XRechnung CIUS I suggest that your InputFactory checks if it just received a ZF file, and extracts it's XML if that is the case.

Requirements are 
* the PDF files might be internally compressed
* the embedded file name may be ZUGFeRD-invoice.xml for zf1, zugferd-invoice.xml for zf2 or factur-x.xml for fx
* (use the real filenames, not just the keys in the dictionary) and 
* the XML files might be embedded in "flat" or "array" notation as well

**Comment by jstaerk** [comment]
My usual sample
[MustangGnuaccountingBeispielRE-20190610_507.pdf](https://github.com/itplr-kosit/validator/files/3892011/MustangGnuaccountingBeispielRE-20190610_507.pdf)
should be EN16931 compliant and satisfy XRechnung but it does not validate 
using the validator-configuration-xrechnung and 
`java -jar validationtool-1.1.1-SNAPSHOT-java8-standalone.jar -s scenarios.xml -o test/reports -h test/instances/*.pdf`
because the RAM:ID is just `urn:cen.eu:en16931:2017` and not `urn:cen.eu:en16931:2017#compliant#urn:xoev-de:kosit:standard:xrechnung_1.2`
so I created a test file which contains this fragment and which seems to work:
[inofficial-zugferd-alteredRAMID.pdf](https://github.com/itplr-kosit/validator/files/3892010/inofficial-zugferd-alteredRAMID.pdf)

**Comment by jstaerk** [comment]
my PR https://github.com/itplr-kosit/validator/pull/39

**Comment by rkottmann** [comment]
Closing discussion in #39 - Hence also closing this issue.

Thx again @jstaerk
