### ISSUE TITLE
NullPointerException beim RelativeUriResolver

### ISSUE THREAD

**Issue by motom001** [itplr-kosit/validator#46]
Verweis auf #45 

NullPointerException beim RelativeUriResolver wenn innerhalb eines XSL die Funktion unparsed-text() verwendet wird.

_Minimal-Variante der scenarios.xml_
[validator-configuration-xrechnung_issue#45.zip](https://github.com/itplr-kosit/validator/files/4415040/validator-configuration-xrechnung_issue.45.zip)

_Logdatei vom Validator:_
[validator.log](https://github.com/itplr-kosit/validator/files/4415063/validator.log)

**Genutzte Versionen:**
- validationtool-1.2.0
- validator-configuration-xrechnung_1.2.2_2019-12-30

Fehler lässt sich jederzeit mit der beigefügten Konfiguration reproduzieren.

**Comment by apenski** [comment]
bitte mal mit validator 1.3.0 prüfen, ob der Fehler noch besteht. Das bereitgestellte Beispiel ist nicht vollständig / kann nicht geladen werden. Können Sie das ggf. nochmal neu zusammenstellen?

**Comment by apenski** [comment]
Ich hab mir das nochmal angesehen. Das funktioniert in 1.3.0 auch noch nicht richtig, der Fehler ist aber durch die Änderungen an der Konfiguration etwas anders.

Im Branch [59-resolving-does-not-work-when-using-xslts-unparsed-text-function](https://github.com/itplr-kosit/validator/tree/59-resolving-does-not-work-when-using-xslts-unparsed-text-function) sollte das Problem behoben sein und wird mit dem Release 1.3.1 ausgeliefert.

Für 1.3.0 lässt sich das Problem mit einer angepassten [ResolvingStrategy](https://github.com/itplr-kosit/validator/blob/master/docs/api.md#configure-sml-security-and-resolving) kurzfristig umgehen. Dazu müsste bei Erzeugung des Prozessors auf die sehr strikte Konfiguration verzichtet werden. Genauer gesagt geht es um [Zeile 86](https://github.com/itplr-kosit/validator/blob/13de7f00a4a51c9b09482e910ccf2d453ffb8d2e/src/main/java/de/kosit/validationtool/impl/xml/StrictRelativeResolvingStrategy.java#L86), die im Prinzip sämtliches Default-Verhalten von Saxon verhindert. Lässt man diese weg, geht auch das Resolving mittels `unparsed-text()`. Voraussetzung ist aber, das man die API verwendet und den Validator nicht im Standalone-Betrieb nutzt.

Bei 1.2.x liegt der Fehler im RelativeUriResolver selbst. Wir werden klären, ob wir dafür noch ein weiteres Release erstellen werden. Mittelfristig werden wir aber nicht zwei version pflegen, sodass ein Umstieg ggf. sinnvoll ist ;)

**Comment by apenski** [comment]
Release 1.3.1 ist verfügbar. Release 1.2.x werden wir diesbzgl. nicht anpassen.
