### ISSUE TITLE
Suffix of report xml is missing

### ISSUE THREAD

**Issue by chmoelders** [itplr-kosit/validator#51]
I do not know if this is the correct repository. Maybe it is related to [itplr-kosit/validator](https://github.com/itplr-kosit/validator/).

Reproduction:
`java -jar validationtool-1.3.1-standalone.jar -s validator-configuration/scenarios.xml  -h validator-configuration/test/testsuite/01.13a-INVOICE_ubl.xml`

Generates files:
01-report.01a-INVOICE_ubl => Suffix is missing
01.01a-INVOICE_ubl-report.html

**Comment by chmoelders** [comment]
@apenski Thank you for the quick response!

**Comment by apenski** [comment]
fixed in master. @chmoelders  maybe you can build and test it.

**Comment by chmoelders** [comment]
@apenski I can confirm that it works.
