### ISSUE TITLE
Invoice filenames containing dots

### ISSUE THREAD

**Issue by kmtlu** [itplr-kosit/validator#52]
If I pass an invoice to the Validator (v1.3.1), whose file name does not contain a dot, the reports are generated with the expected filenames <name>-report.html and <name>-report.xml. E.g. the invoice "`C:\Xrechnung\Export\Invoice\abc.xml`", executed via

`java -jar "C:\Xrechnung\Kosit\lib\validationtool-1.3.1-standalone.jar" -s "C:\Xrechnung\Kosit\xrechnung\conf\scenarios.xml" -r "C:\Xrechnung\Kosit\xrechnung\conf" -h -o "C:\Xrechnung\Export\Bericht" "C:\Xrechnung\Export\Rechnung\abc.xml"`

generated the following reports: "`abc-report.html`" and "`abc-report.xml`"

However, if the file name of the invoice contains a dot, e.g. "`abc.123.xml`", and you call the Validator as above, you will get the reports "`abc.123-report.html`" and "`abc-report.123`". The name of the HTML report looks quite good so far, but the suffix "-report" is moved before dot and the file extension is discarded, so that only what was previously behind the dot, stays there as the file extension.

**Comment by apenski** [comment]
already fixed with #51, releases 1.3.2 will be shipped soon

**Comment by apenski** [comment]
fixed in 1.4.0
