### ISSUE TITLE
`namespace` element content needs trimming

### ISSUE THREAD

**Issue by christian-schlichtherle** [itplr-kosit/validator#56]
First of all, thanks for this awesome project!

I think I found a bug in the scenarios.xml processing. The following works:

```xml
    <namespace prefix="ram">urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:100</namespace>
```

However, the following results in a mismatch:

```xml
    <namespace prefix="ram">urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:100
    </namespace>
```

I guess the element content needs trimming. I haven't tested where else in the XML this would break.

**Comment by apenski** [comment]
yes, the missing trim causes errors. I'll fix this for the next release

**Comment by apenski** [comment]
fixed in master
