### ISSUE TITLE
Probleme mit HTTP Daemon

### ISSUE THREAD

**Issue by stedekay** [itplr-kosit/validator#57]
Wir versuchen derzeit den HTTP Daemon zum Laufen zu bringen und testen das anhand einer gültigen ubl.xml aus der Testsuite aus.
Wenn wir den Befehl: 
`java -jar validationtool-1.3.1-java8-standalone.jar -s scenarios.xml -h ubl.xml`
 ausführen, ist die Antwort auch "ACCEPTABLE", wie erwartet.

Wenn wir den Daemon starten mit: 
`java -jar validationtool-1.3.1-java8-standalone.jar -s scenarios.xml -D -P 8081`
 und dann 
`curl --location --request POST 'http://127.0.0.1:8081' --header 'Content-Type: application/xml' --data-binary './ubl.xml'`
 ausführen erhalten wir folgende Fehlermeldung im Log vom Daemon: 
```
2020-09-25 11:47:24 [INFO] Server /127.0.0.1:8081 started
2020-09-25 11:47:35 [INFO] Checking content of supplied_instance_1
Error on line 1 column 1 of supplied_instance_1:
  SXXP0003: Error reported by XML parser: Content ist nicht zulässig in Prolog.
2020-09-25 11:47:35 [ERROR] No valid scenario configuration found for supplied_instance_1
2020-09-25 11:47:35 [INFO] Finished check of supplied_instance_1 in 168ms
```

Ich hätte erwartet, dass auch mit dem Daemon das Dokument als valide angesehen wird. Was machen wir falsch?

**Comment by apenski** [comment]
das sollte auch so sein. Die Verwendung sieht eigentlich gut aus. Die Fehlermeldungen zeigen ja, dass die Datei nicht als richtige XML-Datei erkannt. Da ich selbst kürzlich einen Fehler im I/O des Daemon entdeckt habe, vermute ich da den Fehler. Ich bin da dran, brauch allerdings noch ein paar Tage, da mir momentan die Zeit dafür fehlt.

**Comment by apenski** [comment]
Ich konnte mir das doch schon anschauen. Grundsätzlich ist curl Aufruf doch nicht ganz richtig.

Mit `--data-binary './ubl.xml'` wird der String `./ubl.xml` an den Server gesendet. 

Korrekt wäre (vgl. [Doku](https://github.com/itplr-kosit/validator/blob/master/docs/daemon.md#access-the-http-interface))

`--data-binary '@ubl.xml'`

Dennoch besteht in der Version 1.3.1 der Fehler mit dem fehlerhaften Einlesen, der bei größeren Dateien auftritt. Dieser ist im Master gefixed. Haben Sie die Möglichkeit den Code zu kompiliieren und damit zu testen? Ansonsten werde ich nächste Woche ein Release erstellen

**Comment by apenski** [comment]
Da der Daemon scheinbar noch nicht so häufig verwendet wird, wären wir auch gern an Feedback aus Entwicklersicht interessiert. Also wenn es da Wünsche, Kritik oder Anregungen gibt, bitte gern teilen

**Comment by stedekay** [comment]
> Korrekt wäre (vgl. [Doku](https://github.com/itplr-kosit/validator/blob/master/docs/daemon.md#access-the-http-interface))
> 
> `--data-binary '@ubl.xml'`

Zu dem Punkt kann ich schonmal folgendes sagen, das hat bei mir nicht funktioniert. Die Datei ubl.xml liegt im gleichen Verzeichnis in dem ich den curl-Befehl abschicke und erhalte dann folgende Meldung:

```
Warning: Couldn't read data from file "/ubl.xml", this makes an empty POST.
No content supplied
```
Im Server-Log erscheint entsprechend nichts.

Ich kann auch mal versuchen den master zu testen, muss hierfür aber mir erst ein wenig Zeit freischaufeln.

**Comment by apenski** [comment]
hm, komisch, bei funktioniert das.
Mein komplettes Kommando:
`curl --location --request POST 'http://127.0.0.1:8080' --header 'Content-Type:
application/xml' --data-binary '@ubl.xml'`

Umgebung:
curl in WSL 1 (Ubuntu)
```
curl 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 OpenSSL/1.1.1 zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
Release-Date: 2018-01-24
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL
```

Der Daemon hat auch eine rudimentäre GUI mit der man testen kann. Einfach mal auf / im Browser gehen und mal schauen, ob das Problem dort auch besteht

**Comment by stedekay** [comment]
Okay, das ist tatsächlich interessant. Über den Browser funktioniert das tatsächlich. Curl war auch eher zum ausprobieren da. Ich habe jetzt eine Anbindung über PHP geschrieben und kann dort ebenfalls das Ergebnis erhalten. Es scheint also zu funktionieren. 

Allerdings erhalte ich auch bei einem invaliden XML einen 200er StatusCode zurück. Das müsste doch ein 406er sein, oder?

**Comment by apenski** [comment]
ja, es müsste ein 406 sein. Du Doku ist schon auf dem Stand von Release 1.4.0 gewesen, welches ich gerade eben freigegeben habe. Bitte mal damit probieren.

Bzgl. des Request: ich vermute das Sie curl an der Stelle nicht richtig nutzen, oder ein Problem mit Ihrer curl Installation besteht. Geht denn der Aufruf von mir, wenn Sie ihn einfach kopieren?

**Comment by stedekay** [comment]
Ah super, sowohl der Status Code als auch das Problem mit curl sind mit 1.4.0 behoben. Vielen Dank für die Hilfe!

Gibt es Interesse daran, die Doku um ein Beispiel zu erweitern, wie man mit PHP darauf zugreift? Könnte ich dann einen PR für bieten.

**Comment by rkottmann** [comment]
> Gibt es Interesse daran, die Doku um ein Beispiel zu erweitern, wie man mit PHP darauf zugreift? Könnte ich dann einen PR für bieten.

Ja, gerne 👍 !
