### ISSUE TITLE
Validierung von zwei unterschiedlichen XRechnungs Versionen

### ISSUE THREAD

**Issue by thomaspz** [itplr-kosit/validator#58]
Wie ist Ihr Vorgehen für die Kompatibilität bei zwei unterschiedlichen XRechnungs-Versionen. Durch die Separierung zwischen Validator und Konfiguration wäre es ja grundsätzlich möglich verschiedene Versionen der XRechnung zu validieren, um so z.b. für einen Übergangszeitraum zwei Versionen der XRechnung validieren zu können.

Wird es grundsätzlich unterstütz / berücksichtigt, dass man mit der aktuellen Validator-Version die aktuelle und mind. die vorherige XRechnungs-Konfiguration nutzen kann oder kann es hierbei ggf. Breaking-Changes geben, so das ggf. auch ein älterer Validator für die vorherige XRechnungs-Konfiguration notwendig wäre?

Oder gehen Sie grundsätzlich davon aus, dass durch die Definition des Gültigkeitszeitraumen in der Spezifikation der XRechnung der Wechsel "hart" zum definierten Termin erfolgen wird/muss und damit ältere Versionen prinzipiell nicht mehr unterstützt werden und somit diese Kompatibilität gar nicht berücksichtigt wird/werden muss?

**Comment by apenski** [comment]
>Wie ist Ihr Vorgehen für die Kompatibilität bei zwei unterschiedlichen XRechnungs-Versionen. Durch die Separierung zwischen Validator und Konfiguration wäre es ja grundsätzlich möglich verschiedene Versionen der XRechnung zu validieren, um so z.b. für einen Übergangszeitraum zwei Versionen der XRechnung validieren zu können.

XRechnung ist  nur EINE Scenario-Konfiguration für den Validator. Es steht jedem Nutzer frei, bestehende Konfiguration anzupassen oder eigene zu erstellen. Dabei müssen die einzelnen Scenarien fachlich auch nichts miteinander zu tun haben. Ich selbst nutze den Validator bspw. in einem Projekt bei ich ich 4 Version der XGewerbeanzeige und eine Version von XJustiz unterstütze. Alles in einer Konfiguration.

Ihr UseCase lässt sich also relativ einfach abbilden. Sie brauchen nur eine Konfiguration mit einzelnen Scenarien für jede zu unterstützende Version. Allerdings wird dies nicht direkt vom XRechnung-Team angeboten. Diese müssten Sie selber erstellen.

Für den Validator gibt es aber die Überlegung, ob nicht mehrere Konfiguration gleichzeitig "geladen" werden können. Das werden wir wohl noch in diesem Jahr umsetzen. 

>Wird es grundsätzlich unterstütz / berücksichtigt, dass man mit der aktuellen Validator-Version die aktuelle und mind. die vorherige XRechnungs-Konfiguration nutzen kann oder kann es hierbei ggf. Breaking-Changes geben, so das ggf. auch ein älterer Validator für die vorherige XRechnungs-Konfiguration notwendig wäre?

Grundsätzlich sollten die Scenario-Konfigurationen mit jeder Version des Validators laufen - abgesehen von Bugs. Im XRechnungs-Kontext wird der Validator in der Version im Bundle angeboten, der während der Weiterentwicklung der Konfiguration genutzt wurde - mit dem also getestet wurde. Man muss nicht diesen verwenden.

>Oder gehen Sie grundsätzlich davon aus, dass durch die Definition des Gültigkeitszeitraumen in der Spezifikation der XRechnung der Wechsel "hart" zum definierten Termin erfolgen wird/muss und damit ältere Versionen prinzipiell nicht mehr unterstützt werden und somit diese Kompatibilität gar nicht berücksichtigt wird/werden muss?

Nein, siehe oben. Genau aus dem Grund untestütze ich auch mehrere Version der XGewerbeanzeige in meinem Projekt, weil auch nach Monaten noch alte Versionen angeliefert werden.
