### ISSUE TITLE
Validationtool (Standalone) stops working at Type error in XSL

### ISSUE THREAD

**Issue by mircokuhlmann** [itplr-kosit/validator#6]
Validating the (incorrect) instance [01.10a-INVOICE_ubl.zip](https://github.com/itplr-kosit/validationtool/files/1685891/01.10a-INVOICE_ubl.zip) leads to a Type error in XSL which in turn leads to an error in the Validationtool:

> [main] INFO de.kosit.validationtool.impl.DefaultCheck - Checking content of instances\01.10a-INVOICE_ubl.xml
> Type error at char 40 in xsl:when/@test on line 276 column 620 of XRechnung-UBL-validation-Invoice.xsl:
>   XPTY0004: A sequence of more than one item is not allowed as the first argument of
>   tokenize() ("#SKONTO#TAGE=7#PROZENT=2.00#", "#SKONTO#TAGE=14#PROZENT=1.00#", ...)
>   in built-in template rule at xsl:apply-templates (file:/C:/Users/Mirco/Desktop/xrechnung-1_1-20171219%20(1)/xrechnung/resources/xrechnung/ubl21/xsl/XRechnung-UBL-validation-Invoice.xsl#199)
>      processing /
> [main] ERROR de.kosit.validationtool.cmd.CommandLineApplication - Can not run schematron validation

Despite the Type error, the Validationtool should continue and generate a validation report.

**Comment by fbuettner-hb** [comment]
The _createReportInput_ internally passed to the XSLT report stylesheet should contain a _processingError_ child element in this case. 

This stylesheet should then generate a _reject_.

**Comment by apenski** [comment]
@mircokuhlmann this seems to be an outdated issue. I don't get any errors with recent development version and recent xrechnung configuration. So I'd like to close this for the moment. Maybe you can test this next release and if the issues occurs again you can reopen this issue

**Comment by mircokuhlmann** [comment]
I checked the instance with the current validator version. I also do not get any errors. 

Closed.
