### ISSUE TITLE
Status code 200 when no scenario matches

### ISSUE THREAD

**Issue by Lorenzschaef** [itplr-kosit/validator#64]
The daemon produces a 200 status code response when no scenario matches. This is unexpected. According to the documentation 200 means the validation was successful.

Edit: Actually, I also get a 200 response code if a scenario matches and the validation fails.

**Comment by apenski** [comment]
which version do you use? Actually with 1.4.0 the response code for failed validation shouldn't be 200. 

What I need to check is behaviour when falling into the falback scenario - e.g. no scenario matches. What would be your expectation regarding response code then?

**Comment by apenski** [comment]
1.4.0 returns in both cases (no scenario match and failed validation) a 406 - at least when use the gui. This feature was added in 1.4.0. Can you confirm, that you used a version < 1.4.0? Then I would ask you to upgrade and will close the issue

**Comment by Lorenzschaef** [comment]
I was indeed still on 1.3.1. The new version behaves as expected. Sorry about that!
