### ISSUE TITLE
`NoSuchMethodError` in `StrictRelativeResolvingStrategy`

### ISSUE THREAD

**Issue by Cakmakli-a** [itplr-kosit/validator#68]
In der Klasse `StrictRelativeResolvingStrategy` passiert folgendens:
```
        // grundsätzlich Feature-konfiguration:
        processor.setConfigurationProperty(Feature.DTD_VALIDATION, false);
        processor.setConfigurationProperty(Feature.ENTITY_RESOLVER_CLASS, "");
        processor.setConfigurationProperty(Feature.XINCLUDE, false);
        processor.setConfigurationProperty(Feature.ALLOW_EXTERNAL_FUNCTIONS, false);
```

Die Signatur der Methode ist folgende `void setConfigurationProperty(String name, Object value)`.
Der Methode wird aber `Feature<Boolean>, boolean` übergeben, was zu einem Problem führt.
Saxon-HE 9.9.1-7 setze ich auch ein. 

Hier die Exception:
```
java.lang.NoSuchMethodError: net.sf.saxon.s9api.Processor.setConfigurationProperty(Lnet/sf/saxon/lib/Feature;Ljava/lang/Object;)V

	at de.kosit.validationtool.impl.xml.StrictRelativeResolvingStrategy.createProcessor(StrictRelativeResolvingStrategy.java:106)
	at de.kosit.validationtool.impl.xml.BaseResolvingStrategy.getProcessor(BaseResolvingStrategy.java:52)
	at de.kosit.validationtool.config.ConfigurationLoader.build(ConfigurationLoader.java:136)
```

**Comment by apenski** [comment]
Bitte den classpath kontrollieren, da scheint eine ältere Saxon-Version mit inkludiert zu sein. Die String-Variante wurde inzwischen als deprecated markiert:

![grafik](https://user-images.githubusercontent.com/19796680/99500507-c141dc80-297a-11eb-91c9-2c7978b99a87.png)

**Comment by apenski** [comment]
kann ich davon ausgehen, das der Fehler nach Korrekt des Classpath nicht mehr auftritt, somit kein Anpassungsbedarf beim Validator liegt?

**Comment by Cakmakli-a** [comment]
Eine ältere Saxon-Version hat sich eingeschichen. Diese exkludiert und es lief.
