### ISSUE TITLE
Reverse Charge working?

### ISSUE THREAD

**Issue by hypers1** [itplr-kosit/validator#69]
Does reverse charge (TAX Catory Code AE) work and is correct validated?
I cannot validate documents with Reverse Charge:

> [BR-AE-02]-An Invoice that contains an Invoice line (BG-25) where the Invoiced item VAT category code (BT-151) is “Reverse charge” shall contain the Seller VAT Identifier (BT-31), the Seller Tax registration identifier (BT-32) and/or the Seller tax representative VAT identifier (BT-63) and the Buyer VAT identifier (BT-48) and/or the Buyer legal
> 
> [BR-AE-10]-A VAT Breakdown (BG-23) with VAT Category code (BT-118) "Reverse charge" shall have a VAT exemption reason code (BT-121), meaning "Reverse charge" or the VAT exemption reason text (BT-120) "Reverse charge" (or the equivalent standard text in another language).
> 
> [BR-AE-04]-An Invoice that contains a Document level charge (BG-21) where the Document level charge VAT category code (BT-102) is “Reverse charge” shall contain the Seller VAT Identifier (BT-31), the Seller tax registration identifier (BT-32) and/or the Seller tax representative VAT identifier (BT-63) and the Buyer VAT identifier (BT-48) and/or the Buyer legal registration identifier (BT-47).

I have not found any errors in the file, considering the documentation.
Here is the xml code that is not being successfully validated:

<?xml version="1.0" encoding="utf-8"?>
<rsm:CrossIndustryInvoice xmlns:a="urn:un:unece:uncefact:data:standard:QualifiedDataType:100" xmlns:rsm="urn:un:unece:uncefact:data:standard:CrossIndustryInvoice:100" xmlns:qdt="urn:un:unece:uncefact:data:standard:QualifiedDataType:100" xmlns:ram="urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:100" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:udt="urn:un:unece:uncefact:data:standard:UnqualifiedDataType:100">
  <rsm:ExchangedDocumentContext>
    <ram:GuidelineSpecifiedDocumentContextParameter>
      <ram:ID>urn:cen.eu:en16931:2017#compliant#urn:xoev-de:kosit:standard:xrechnung_1.2</ram:ID>
    </ram:GuidelineSpecifiedDocumentContextParameter>
  </rsm:ExchangedDocumentContext>
  <rsm:ExchangedDocument>
    <ram:ID>18383</ram:ID>
    <ram:TypeCode>380</ram:TypeCode>
    <ram:IssueDateTime>
      <udt:DateTimeString format="102">20201127</udt:DateTimeString>
    </ram:IssueDateTime>
  </rsm:ExchangedDocument>
  <rsm:SupplyChainTradeTransaction>
    <ram:IncludedSupplyChainTradeLineItem>
      <ram:AssociatedDocumentLineDocument>
        <ram:LineID>1</ram:LineID>
      </ram:AssociatedDocumentLineDocument>
      <ram:SpecifiedTradeProduct>
        <ram:SellerAssignedID>1</ram:SellerAssignedID>
        <ram:Name>HSW-Tür Instandsetzung</ram:Name>
      </ram:SpecifiedTradeProduct>
      <ram:SpecifiedLineTradeAgreement>
        <ram:GrossPriceProductTradePrice>
          <ram:ChargeAmount>52.00</ram:ChargeAmount>
        </ram:GrossPriceProductTradePrice>
        <ram:NetPriceProductTradePrice>
          <ram:ChargeAmount>52.00</ram:ChargeAmount>
        </ram:NetPriceProductTradePrice>
      </ram:SpecifiedLineTradeAgreement>
      <ram:SpecifiedLineTradeDelivery>
        <ram:BilledQuantity unitCode="HUR">4.00</ram:BilledQuantity>
      </ram:SpecifiedLineTradeDelivery>
      <ram:SpecifiedLineTradeSettlement>
        <ram:ApplicableTradeTax>
          <ram:TypeCode>VAT</ram:TypeCode>
          <ram:ExemptionReason>Umkehrung der Steuerschuldnerschaft</ram:ExemptionReason>
          <ram:CategoryCode>AE</ram:CategoryCode>
          <ram:RateApplicablePercent>0.00</ram:RateApplicablePercent>
        </ram:ApplicableTradeTax>
        <ram:SpecifiedTradeSettlementLineMonetarySummation>
          <ram:LineTotalAmount>208.00</ram:LineTotalAmount>
        </ram:SpecifiedTradeSettlementLineMonetarySummation>
      </ram:SpecifiedLineTradeSettlement>
    </ram:IncludedSupplyChainTradeLineItem>
    <ram:ApplicableHeaderTradeAgreement>
      <ram:BuyerReference>123456789</ram:BuyerReference>
      <ram:SellerTradeParty>
        <ram:ID>116078</ram:ID>
        <ram:Name>Mustermann GmbH</ram:Name>
        <ram:DefinedTradeContact>
          <ram:PersonName>Wolfgang Muster</ram:PersonName>
          <ram:TelephoneUniversalCommunication>
            <ram:CompleteNumber>069-12335</ram:CompleteNumber>
          </ram:TelephoneUniversalCommunication>
          <ram:EmailURIUniversalCommunication>
            <ram:URIID>mail@muster.de</ram:URIID>
          </ram:EmailURIUniversalCommunication>
        </ram:DefinedTradeContact>
        <ram:PostalTradeAddress>
          <ram:PostcodeCode>60388</ram:PostcodeCode>
          <ram:LineOne>Musterstrasse 4</ram:LineOne>
          <ram:CityName>Frankfurt am Main</ram:CityName>
          <ram:CountryID>DE</ram:CountryID>
        </ram:PostalTradeAddress>
        <ram:SpecifiedTaxRegistration>
          <ram:ID schemeID="FC">04523149435</ram:ID>
        </ram:SpecifiedTaxRegistration>
        <ram:SpecifiedTaxRegistration>
          <ram:ID schemeID="VA">DE152338654</ram:ID>
        </ram:SpecifiedTaxRegistration>
      </ram:SellerTradeParty>
      <ram:BuyerTradeParty>
        <ram:ID>10099</ram:ID>
        <ram:Name>DB Station&amp;Service AG RB Mitte</ram:Name>
        <ram:DefinedTradeContact>
          <ram:PersonName>Klaus Koffer</ram:PersonName>
        </ram:DefinedTradeContact>
        <ram:PostalTradeAddress>
          <ram:PostcodeCode>10115</ram:PostcodeCode>
          <ram:LineOne>Elisabeth-Schwarzhaupt-Platz 1</ram:LineOne>
          <ram:CityName>Berlin</ram:CityName>
          <ram:CountryID>DE</ram:CountryID>
        </ram:PostalTradeAddress>
        <ram:SpecifiedTaxRegistration>
          <ram:ID schemeID="VA">DE152138634</ram:ID>
        </ram:SpecifiedTaxRegistration>
        <ram:SpecifiedTaxRegistration>
          <ram:ID schemeID="FC">04523249415</ram:ID>
        </ram:SpecifiedTaxRegistration>
      </ram:BuyerTradeParty>
      <ram:BuyerOrderReferencedDocument>
        <ram:IssuerAssignedID />
      </ram:BuyerOrderReferencedDocument>
    </ram:ApplicableHeaderTradeAgreement>
    <ram:ApplicableHeaderTradeDelivery>
      <ram:ActualDeliverySupplyChainEvent>
        <ram:OccurrenceDateTime>
          <udt:DateTimeString format="102">20201123</udt:DateTimeString>
        </ram:OccurrenceDateTime>
      </ram:ActualDeliverySupplyChainEvent>
      <ram:DeliveryNoteReferencedDocument>
        <ram:IssuerAssignedID>22138</ram:IssuerAssignedID>
      </ram:DeliveryNoteReferencedDocument>
    </ram:ApplicableHeaderTradeDelivery>
    <ram:ApplicableHeaderTradeSettlement>
      <ram:InvoiceCurrencyCode>EUR</ram:InvoiceCurrencyCode>
      <ram:SpecifiedTradeSettlementPaymentMeans>
        <ram:TypeCode>1</ram:TypeCode>
        <ram:Information>Rechnung</ram:Information>
        <ram:PayeePartyCreditorFinancialAccount>
          <ram:IBANID>DE54500800000192632400</ram:IBANID>
          <ram:AccountName>Mustermann GmbH</ram:AccountName>
        </ram:PayeePartyCreditorFinancialAccount>
        <ram:PayeeSpecifiedCreditorFinancialInstitution>
          <ram:BICID>DRESDEFFXXX</ram:BICID>
        </ram:PayeeSpecifiedCreditorFinancialInstitution>
      </ram:SpecifiedTradeSettlementPaymentMeans>
      <ram:ApplicableTradeTax>
        <ram:CalculatedAmount>0.00</ram:CalculatedAmount>
        <ram:TypeCode>VAT</ram:TypeCode>
        <ram:BasisAmount>233.00</ram:BasisAmount>
        <ram:CategoryCode>AE</ram:CategoryCode>
        <ram:RateApplicablePercent>0.00</ram:RateApplicablePercent>
      </ram:ApplicableTradeTax>
      <ram:SpecifiedTradeAllowanceCharge>
        <ram:ChargeIndicator>
          <udt:Indicator>true</udt:Indicator>
        </ram:ChargeIndicator>
        <ram:BasisAmount>0.00</ram:BasisAmount>
        <ram:ActualAmount>25.00</ram:ActualAmount>
        <ram:Reason>Lieferpauschale</ram:Reason>
        <ram:CategoryTradeTax>
          <ram:TypeCode>VAT</ram:TypeCode>
          <ram:CategoryCode>AE</ram:CategoryCode>
          <ram:RateApplicablePercent>0.00</ram:RateApplicablePercent>
        </ram:CategoryTradeTax>
      </ram:SpecifiedTradeAllowanceCharge>
      <ram:SpecifiedTradePaymentTerms>
        <ram:Description>10 Tage 3% Skonto, 30 Tage netto</ram:Description>
        <ram:DueDateDateTime>
          <udt:DateTimeString format="102">20201227</udt:DateTimeString>
        </ram:DueDateDateTime>
      </ram:SpecifiedTradePaymentTerms>
      <ram:SpecifiedTradeSettlementHeaderMonetarySummation>
        <ram:LineTotalAmount>208.00</ram:LineTotalAmount>
        <ram:ChargeTotalAmount>25.00</ram:ChargeTotalAmount>
        <ram:AllowanceTotalAmount>0.00</ram:AllowanceTotalAmount>
        <ram:TaxBasisTotalAmount>233.00</ram:TaxBasisTotalAmount>
        <ram:TaxTotalAmount currencyID="EUR">0.00</ram:TaxTotalAmount>
        <ram:GrandTotalAmount>233.00</ram:GrandTotalAmount>
        <ram:DuePayableAmount>233.00</ram:DuePayableAmount>
      </ram:SpecifiedTradeSettlementHeaderMonetarySummation>
    </ram:ApplicableHeaderTradeSettlement>
  </rsm:SupplyChainTradeTransaction>
</rsm:CrossIndustryInvoice>

**Comment by landrix** [comment]
For me it works

You should place a exemption reason text

Is it all explained in your validation result

**Comment by hypers1** [comment]
What have I missed? 
The text is available: <ram:ExemptionReason>Reversal of tax liability</ram:ExemptionReason>

I don't understand why the validator criticizes the tax identification numbers although they are included.

**Comment by landrix** [comment]
Sry you are right
I have to look at a bigger screen first

**Comment by hypers1** [comment]
I have checked the documentation against my file several times, but I can't find any error in the file, so I'm not sure if it could be an error in the validation.

**Comment by landrix** [comment]
Im also generating invoices with reverse charge without validation errors

I can look tomorrow

**Comment by hypers1** [comment]
That would be very nice. Thank very much. An example file from you that works could be help me, too. 
Danke :)

**Comment by landrix** [comment]
Can you attach your document as zip

**Comment by hypers1** [comment]
Yes
[Uploading Test.zip…]()

**Comment by hypers1** [comment]
I found out the reason for the first and the last error: When I change the schemeID from "VA" to "VAT" the errors are gone.

```
        <ram:SpecifiedTaxRegistration>
          <ram:ID schemeID="VAT">DE152738634</ram:ID>
        </ram:SpecifiedTaxRegistration>

```


I've found two different (official?) documentations: One says it shoud be "VA", the other one says it should be "VAT".
I am a little confused about this. What is correct?


It is still unclear why an ExemptionReason is required in path 

```
/Rsm:CrossIndustryInvoice/rsm:SupplyChainTradeTransaction/ram:ApplicableHeader
TradeSettlement/ram:ApplicableTradeTax/ram:ExemptionReason
```

But it runs on an error when I specify it:
```

    <ram:ApplicableHeaderTradeSettlement>
      <ram:InvoiceCurrencyCode>EUR</ram:InvoiceCurrencyCode>
      <ram:SpecifiedTradeSettlementPaymentMeans>
        <ram:TypeCode>1</ram:TypeCode>
        <ram:Information>Rechnung</ram:Information>
        <ram:PayeePartyCreditorFinancialAccount>
          <ram:IBANID>DE54500800000192632400</ram:IBANID>
          <ram:AccountName>Mustermann GmbH</ram:AccountName>
        </ram:PayeePartyCreditorFinancialAccount>
        <ram:PayeeSpecifiedCreditorFinancialInstitution>
          <ram:BICID>DRESDEFFXXX</ram:BICID>
        </ram:PayeeSpecifiedCreditorFinancialInstitution>
      </ram:SpecifiedTradeSettlementPaymentMeans>
      <ram:ApplicableTradeTax>
        <ram:CalculatedAmount>0.00</ram:CalculatedAmount>
        <ram:TypeCode>VAT</ram:TypeCode>
        <ram:BasisAmount>233.00</ram:BasisAmount>
        <ram:CategoryCode>AE</ram:CategoryCode>
        <ram:RateApplicablePercent>0.00</ram:RateApplicablePercent>
		<ram:ExemptionReason>Reverse Charge</ram:ExemptionReason>
      </ram:ApplicableTradeTax>
```


`Invalid content was found starting with element '{"urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:100":ExemptionReason}'. One of '{"urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:100":SpecifiedTradeAccountingAccount, "urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:100":ServiceSupplyTradeCountry, "urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:100":BuyerRepayableTaxSpecifiedTradeAccountingAccount, "urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:100":SellerPayableTaxSpecifiedTradeAccountingAccount, "urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:100":SellerRefundableTaxSpecifiedTradeAccountingAccount, "urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:100":BuyerDeductibleTaxSpecifiedTradeAccountingAccount, "urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:100":BuyerNonDeductibleTaxSpecifiedTradeAccountingAccount, "urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:100":PlaceApplicableTradeLocation}' is expected.
`

**Comment by landrix** [comment]
it works now

**Comment by landrix** [comment]
```
    <ram:GuidelineSpecifiedDocumentContextParameter>
      <ram:ID>urn:cen.eu:en16931:2017#compliant#urn:xoev-de:kosit:standard:xrechnung_2.0</ram:ID>
    </ram:GuidelineSpecifiedDocumentContextParameter>
```

must be set
