### ISSUE TITLE
BR-S-08 

### ISSUE THREAD

**Issue by rhedrich** [itplr-kosit/validator#70]
Hey there, always getting the error:
BR-S-08-For each different value of VAT category rate (BT-119) where the VAT category code (BT-118) is "Standard rated", the VAT category taxable amount (BT-116) in a VAT breakdown (BG-23) shall equal the sum of Invoice line net amounts (BT-131) plus the sum of document level charge amounts (BT-99) minus the sum of document level allowance amounts (BT-92) where the VAT category code (BT-151, BT-102, BT-95) is "Standard rated" and the VAT rate (BT-152, BT-103, BT-96) equals the VAT category rate (BT-119).
For every xRechnung 1.2 and xRechnung 2.0 that i created.
Although the price amounts etc. are perfectly matching.
Same invoice, same values etc. is validating fine with the zugferd profiles.
This only happens when validating xRechnung, here with the validator or any other validator on the net.
Maybe someone could give me and hand, and check the invoice and give me a little hint why that is?
Can i get any help on this from anyone?

**Comment by rkottmann** [comment]
Hi,

BR-S-08 is a Rule from the CEN Schematron which we are in the validation configuration. CEN maintains and discusses such issues here https://github.com/ConnectingEurope/eInvoicing-EN16931/

Please contact them.

**Comment by rkottmann** [comment]
hence we can not fix it here therefore I close it
