### ISSUE TITLE
Cannot cast object Exception bei Api Nutzung

### ISSUE THREAD

**Issue by Moetez16** [itplr-kosit/validator#73]
Guten Tag,

ich versuche das Validationtool in meine Anwendung zu nutzen und habe da einige Probleme. 

Könnt Ihr mir hier weiterhelfen? 

Danke.
 
Wenn ich Ihr einfaches Beispiel von https://github.com/itplr-kosit/validator/blob/master/docs/api.md nehme, bekomme ich immer:
Cannot cast object 'de.kosit.validationtool.config.ConfigurationLoader@475d59c0' with class 'de.kosit.validationtool.config.ConfigurationLoader' to class 'de.kosit.validationtool.api.Configuration'

Code: 
```
URL scenarios = this.getClass().getClassLoader().getResource("scenarios.xml")
Configuration config = Configuration.load(scenarios.toURI())
Check validator = new DefaultCheck(config);
```

Alternative habe ich folgendes benutzt:
```
URL scenarios = this.getClass().getClassLoader().getResource("scenarios.xml")
Configuration config = Configuration.load(scenarios.toURI()).setResolvingMode(ResolvingMode.STRICT_LOCAL)
                .build();
```

Ich bekomme dann: 
`Can not disable external DTD access. Maybe an unsupported JAXP implementation is used.`

**Comment by apenski** [comment]
> Cannot cast object 'de.kosit.validationtool.config.ConfigurationLoader@475d59c0' with class 'de.kosit.validationtool.config.ConfigurationLoader' to class 'de.kosit.validationtool.api.Configuration'

 da hat sich ein Fehler in der Doku eingeschlichen. Es muss heißen:

`Configuration.load(scenarios.toURI()).build()`

Hintergrund: man kann die geladene Konfiguration mit dem Builder noch etwas anpassen. Ich denke da müssen wir die API noch etwas selbsterklärender gestalten.

> Can not disable external DTD access. Maybe an unsupported JAXP implementation is used.

der Validator setzt bzgl. Security auf die XML-Implementierung vom OpenJDK. Wenn diese nicht verwendet wird (nicht OpenJDK oder XercesJ im Classpath o.ä.) kann die XML-Sicherheit nicht gewährleistet werden. Um die Sicherheit nicht gefährden, hab wir da auch keinen Ignore-Switch o.ä.

Möchte man das trotzdem machen, muss man eine eigene Resolving-Strategie entwickeln (also die XML-Factories in konfigurierter Form bereitstellen). Siehe [Security Dokumentation](https://github.com/itplr-kosit/validator/blob/master/docs/api.md#configure-xml-security-and-resolving)

**Comment by Moetez16** [comment]
Danke fuer die Informationen.

Welche OpenJDK Distributions und Version sollte man am besten nutzen bzw. was nutzt Ihr eigentlich?

**Comment by apenski** [comment]
also eigentlich alles was als als OpenJDK-Distribution durchgeht, sollte gehen. Wir testen aktiv die in der [CI-Definition](https://github.com/itplr-kosit/validator/blob/master/.gitlab-ci.yml) aufgeführten

**Comment by asc-schleupen** [comment]
Hallo,

wir sind auf den gleichen Fehler gelaufen
 
 	```
URL scenarios = this.getClass().getClassLoader().getResource("/resources/scenarios.xml");
	Configuration config = Configuration.load(scenarios.toURI()).build();
```
			
Das Laden der Konfiguration führt zu folgender Exception

```
2020-12-18 08:50:13,514 ERROR [de.schleupen.cs.ap.bi.birtreportingservice.businesscases.XRechnungValidationControllerImpl] (default task-1) Fehler beim Erstellen des Prüfberichts: java.lang.IllegalStateException: Can not disable external DTD access. Maybe an unsupported JAXP implementation is used.
	at deployment.BirtReportingService.war//de.kosit.validationtool.impl.xml.BaseResolvingStrategy.setProperty(BaseResolvingStrategy.java:85)
	at deployment.BirtReportingService.war//de.kosit.validationtool.impl.xml.BaseResolvingStrategy.disableExternalEntities(BaseResolvingStrategy.java:127)
	at deployment.BirtReportingService.war//de.kosit.validationtool.impl.xml.BaseResolvingStrategy.disableExternalEntities(BaseResolvingStrategy.java:115)
	at deployment.BirtReportingService.war//de.kosit.validationtool.impl.xml.StrictRelativeResolvingStrategy.createSchemaFactory(StrictRelativeResolvingStrategy.java:91)
	at deployment.BirtReportingService.war//de.kosit.validationtool.impl.ContentRepository.<init>(ContentRepository.java:99)
	at deployment.BirtReportingService.war//de.kosit.validationtool.config.ConfigurationLoader.build(ConfigurationLoader.java:137)
	
[xercesImpl-2.12.0.SP02.zip](https://github.com/itplr-kosit/validator/files/5714541/xercesImpl-2.12.0.SP02.zip)


```
es wird folgendes JDK verwendet

java --version
openjdk 11.0.8 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.8+10, mixed mode)

Die Xerces Implementierung kommt durch den Wildfly-Server Version (>= 18.0.1) : xercesImpl-2.12.0.SP02.jar

Die Prüfung des JDKs in BaseResolvingStrategy.isOpenJdkXmlImplementationAvailable ist erfolgreich. Welche Optionen haben wir die Prüfung zum Laufen zu bringen?

**Comment by Moetez16** [comment]
JDK bei mir: 

adopt-openj9-1.8.0_265

**Comment by Cakmakli-a** [comment]
@asc-schleupen 
Hab das gleiche Problem. Nur kommt bei mir ein JBoss zum Einsatz und der liefert Xerces (xercesImpl-2.11.0) gleich mit. 
Die `SchemaFactory`, die von Xerces implementiert wird mit `org.apache.xerces.jaxp.validation.XMLSchemaFactory`
läßt sicher allerdings nicht konfigurieren wie ich feststellen mußte.
Wie schon @apenski erwähnt hat, solte man eine eigene Resolving-Strategie entwickeln.
In dieser habe ich allerdings die `com.sun.org.apache.xerces.internal.jaxp.validation.XMLSchemaFactory`
eingesetzt und festgestellt, dass diese sich konfigurieren läßt.

**Comment by asc-schleupen** [comment]
@Cakmakli-a 
Vielen Dank für den Tipp. Es hat funktioniert. Die CustomStrategy habe ich von StrictLocalResolvingStrategy übernommen und die createSchemaFactory-Methode wie folgt überschrieben:

```
@Override
public SchemaFactory createSchemaFactory() {
		forceOpenJdkXmlImplementation();
		final SchemaFactory sf = SchemaFactory.newInstance(XMLConstants.W3C_XML_SCHEMA_NS_URI, "com.sun.org.apache.xerces.internal.jaxp.validation.XMLSchemaFactory", this.getClass().getClassLoader() );
		disableExternalEntities(sf);		
		allowExternalSchema(sf, "vfs");
		return sf;
	}
```
