### ISSUE TITLE
Use JAXBContext.newInstance( String, ClassLoader)

### ISSUE THREAD

**Issue by rgra** [itplr-kosit/validator#80]
Would it be possible to change 
`de.kosit.validationtool.impl.ConversionService.initialize(String)`
to use 
`JAXBContext.newInstance(contextPath, ConversionService.class.getClassLoader())`
instead of 
`JAXBContext.newInstance(contextPath)`
otherwise I'm getting class loading issues on Java11 in the Equinox OSGi container.

**Comment by apenski** [comment]
Definitely possible! Changed the code accordingly and will provide a patch release soon.
