### ISSUE TITLE
Generate report.html with Application User Interface

### ISSUE THREAD

**Issue by pehaas** [itplr-kosit/validator#81]
Hi,
is it planed to make the generation of report.html available for the Application User Interface.
Of course I am able to solve this by changing the access modifier ExtractHtmlContentAction to public an use it like 
`DefaultCheck validator = new DefaultCheck(config);
 validator.getCheckSteps().add(new ExtractHtmlContentAction(validator.getContentRepository(), resultOutputDirectory));`

but it would be nice to have this functionality without changing your code.

LG

**Comment by apenski** [comment]
There are no such plans. However, we are currently in transition phase to a version 2.0 which changes the way how reports are generated. It let's you define multiple reports. One reason for this is, that we want to allow creation extra html. The html fragments don't have to be included into the main report.

Easiest for the moment would be to just  copy the code of ExtractHtmlContentAction into an own class. Then you don't need to modify the validator code.
