### ISSUE TITLE
Illegal access operation error messages

### ISSUE THREAD

**Issue by MaximilianB134** [itplr-kosit/validator#87]
Hello,

we are using the validator in the standalone variant in version 1.4.2.
Our java version is the following:
```
openjdk 11.0.6 2020-01-14
OpenJDK Runtime Environment (build 11.0.6+10-suse-3.39.2-x8664)
OpenJDK 64-Bit Server VM (build 11.0.6+10-suse-3.39.2-x8664, mixed mode)
```

The commandline we use to run the validator is: `java -jar /path/to/validator/validationtool-1.4.2-standalone.jar -s /path/to/scenario.xml -o /outputdirectory -h /inputfile`

The validator is called from a php process via exec(). Our server admin informed us that (seemingly) every call of the validation tool leads to the following error messages in the server log. Additionally the tool uses so much memory that the server begins swapping and we then get performance problems.

```
[Thu Oct 07 00:31:15.514374 2021] [core:notice] [pid 8039] AH00052: child pid 5978 exit signal Segmentation fault (11)
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.sun.xml.bind.v2.runtime.reflect.opt.Injector (file:/path/to/validationtool/validationtool-1.4.2-standalone.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int)
WARNING: Please consider reporting this to the maintainers of com.sun.xml.bind.v2.runtime.reflect.opt.Injector
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
zend_mm_heap corrupted
[Thu Oct 07 23:31:16.418880 2021] [core:notice] [pid 8039] AH00052: child pid 29294 exit signal Segmentation fault (11)
[Fri Oct 08 00:31:12.370131 2021] [core:notice] [pid 8039] AH00052: child pid 22054 exit signal Segmentation fault (11)
[Fri Oct 08 10:31:12.258721 2021] [core:notice] [pid 8039] AH00052: child pid 20432 exit signal Segmentation fault (11)
zend_mm_heap corrupted
```

Can you please help us with this issue? Thanks in advance!

**Comment by phax** [comment]
The validator somehow ships with a "daemon" mode, so that it can run in the background. Especially the initial compilation of the Schematron stuff takes time. See more at https://github.com/itplr-kosit/validator#daemon-mode
Alternatively try running the "Java 8" version with Java 1.8 JDK - maybe that helps...

**Comment by apenski** [comment]
ohh sorry, I haven't seen the issue yet. First of all, @phax is right, startup is very expensive and the daemon mode is a better option. Your app can then access the validator functionality via http.

Regarding the failing: There is not enough output to say what's going wrong here. The warning comes from using jaxb. We'll geet rid of that in future versions by upgrading the dependency. This should have nothing to do with the segmentation fault. 

Your java environment looks fine and should work. OpenJDK 11 is the main dev environment and we do also unit testing with jdk 11 (despite various other jdk versions). Is the installation of Java somewhat buggy? Any other output? Does something interrupt the java process? 

Does the generated commandline work, if you run it in a terminal?

**Comment by svanteschubert** [comment]
These warnings will likely disappear when the validator is upgraded to JAXB 2.4, which enables the [Java Platform Module System (JPMS)](https://javaee.github.io/jaxb-v2/doc/user-guide/ch02.html#a-2-4-0)
see also
https://stackoverflow.com/questions/50237516/proper-fix-for-java-10-complaining-about-illegal-reflection-access-by-jaxb-impl

**Comment by apenski** [comment]
We will upgrade with the next release.

Labeled "outdated" since imho the main "issue" here, is not the warning, but the wrong usage (load on every validation, standalone vs daemon etc.)
