### ISSUE TITLE
unitCode="KTM" not valid?

### ISSUE THREAD

**Issue by aronkankel** [itplr-kosit/validator#89]
If I use unitCode="KTM" für BilledQuantity or BasisQuantity I get BR-CL-23:

[BR-CL-23]-Unit code MUST be coded according to the UN/ECE Recommendation 20 with Rec 21 extension

In UN/ECE are both "KTM" and "KMT" to use for "kilometre".
https://www.xrepository.de/api/xrepository/urn:xoev-de:kosit:codeliste:rec20_2:technischerBestandteilGenericode

Why is "KTM" not supported?

**Comment by apenski** [comment]
well, this is actually not a question for validator, but for [xrechnung scenario](https://github.com/itplr-kosit/validator-configuration-xrechnung). Please raise the issue there.

**Comment by larsroelkerdenker** [comment]
@aronkankel KTM was set to deleted by UN/CEFACT and CEN schematrons already implemented this. We will update our versions of the code list during January and remove the deleted codes.

For any further questions please contact xrechnung@finanzen.bremen.de
