### ISSUE TITLE
Multiple scenarios files?

### ISSUE THREAD

**Issue by Lorenzschaef** [itplr-kosit/validator#90]
I need to validate both XRechnung 2.0 and XRechnung 2.1.1 files. If I install the updated validation rules, version 2.0 is no longer supported and vice versa.

Is there a way to run the validator using two scenarios files at the same time?

I tried repeating the `-s` flag, but the second one is simply ignored.

**Comment by apenski** [comment]
This feature is not yet released yet, but available in master and not quality assured yet. I can not say when we will release a new version. There is no actual development going on at the moment, since there is no new feature request, and this feature was not prioritized.

@rkottmann any plans on this?

**Comment by DerHamm** [comment]
Is there a recommended workaround to adress this issue? Two ideas come to my mind:

Is it legitimate to change the CustomizationID (ubl format) to contain the currently supported version number? E.g. I have a XRechnung in with this CustomizationID: "urn:cen.eu:en16931:2017#compliant#urn:xoev-de:kosit:standard:xrechnung_2.0". If I change the last character to "1", the validator will accept that file again. 

Or would it be a better approach to distribute multiple scenario files, read the CustomizationID out and then use the scenario file with the version corresponding to the XRechnung currently being processed?

In my current situation I will either have to implement one of those approaches or my management will require me to remove the validator and "just look for the fields we need for what we want to do", which is effectively writing my own validator, which sounds like a bad idea.

Any help is much appreciated.

**Comment by msccip** [comment]
Hi,
we manage this problem by changing the scenarios.xml i.e. for UBL Invoice in the following way to accept versions 2.0 and 2.1:

    <match>exists(/invoice:Invoice[ cbc:CustomizationID/text() = 'urn:cen.eu:en16931:2017#compliant#urn:xoev-de:kosit:standard:xrechnung_2.0' or cbc:CustomizationID/text() = 'urn:cen.eu:en16931:2017#compliant#urn:xoev-de:kosit:standard:xrechnung_2.1']) </match>

and for the other scenarios accordingly. This adaption is easy and fast to do and to test. And has worked well last year with version 1.2 and 2.0.

**Comment by DerHamm** [comment]
Hi, thank you for the fast response.

I tried your solution with a <match> tag for the versions 2.0 - 2.2. I tested it with [this test file](https://github.com/itplr-kosit/xrechnung-testsuite/blob/master/src/test/business-cases/standard/01.01a-INVOICE_ubl.xml) from the test-suite repository and it works fine.

**Comment by apenski** [comment]
And just to clarify: it's not a workaround. It's a design concept of the validator. Most people just consider the xrechnung configuration as something official and do not want to modify it. But it's not. It's just a reference/base implementation for the latest rules. You can adapth this to your needs (my personal opinion - I'm not invovled in xrechnung configuration development)

Thanks @msccip for pointing out. We had several direct feature requests for supporting multiple scenario files, that the obvious solution did not come into my mind when I answered the feauture request 😒

Nevertheless, the next major version will support multiple scenario files. But thats only API / CLI sugar. Internally it's just a merge of the configurations. Order of scenarios (and files) will be important as well as a  good "match" configuration for each scenario. 

That being being sayd, I would not assume, that running a validator with configurations for xrechnung vX and vY will run fine without some tweaks to configurations unless the XRechnung team explicitly supports this by defining a version specific match.

**Comment by apenski** [comment]
There is support for multiple scenario files now. Scenarios are run in order of occurence, so it's up to the user to configure the scenarios carefully

Fixed in main.

**Comment by quotschmacher** [comment]
> There is support for multiple scenario files now. Scenarios are run in order of occurence, so it's up to the user to configure the scenarios carefully
> 
> Fixed in main.

How do I have to open the validator now in daemon mode? Just pass a comma seperated list to the '-s' parameter?
