### ISSUE TITLE
High Memory Usage

### ISSUE THREAD

**Issue by ado-pp** [itplr-kosit/validator#96]
Some of our daemons got killed because of high memory usage of the validator-tool. 

Attached also the Apache Log:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.sun.xml.bind.v2.runtime.reflect.opt.Injector (file:xxx/validationtool-1.4.2-standalone.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int)
WARNING: Please consider reporting this to the maintainers of com.sun.xml.bind.v2.runtime.reflect.opt.Injector
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

How much Memory does the tool actually need?

**Comment by apenski** [comment]
Well, memory usage of the daemon itself should be very little (few megabytes). Depending on the documents and the scenarios you use, memory consumption can be high. E.g. xrechnung visualisation can lead to high memory consumption under certain circumstances (see [issue 73](https://github.com/itplr-kosit/validator-configuration-xrechnung/issues/73)). 

The attached log just shows some warnings from jaxb, which is using some reflection operation which won't be allowed in future java version. For next release, we will upgrade the jaxb version and the messages will disappear. 

To better investigate whether you we have an issue here, we need more information. What is memory consumption after startup? When is the daemon killed? What was the current action (validating xrechnung document?), when the daemon got killed? Which java version is used? Which jar is used? etc. etc.
