### ISSUE TITLE
Fehlermeldung "Leitweg-ID ungültig" bei ungültigen XML-Dateien umformulieren

### ISSUE THREAD

**Issue by lukas-menzel-nortal** [itplr-kosit/validator#97]
Aus dem Support Jour Fixe wurde ein Verbesserungsvorschlag geäußert:

Fehlermeldung "Leitweg-ID ungültig" bei ungültigen XML-Dateien umformulieren, sodass deutlicher wird, dass Erstellung von Rechnungen in Word und Export als XML nicht korrekt ist. Korrekterweise sollte die Fehlermeldung darauf hinweisen, dass das Abspeichern einer in Word erstellten Rechnung als XML keine korrekt formatierte E-Rechnung ist und nicht eine ungültige Leitweg ID dass Grundproblem ist.

**Comment by apenski** [comment]
Hi @lukas-menzel-nortal,

das Ticket scheint mir fehlgeleitet. Entweder ist die [XRechnung Konfiguration](https://github.com/itplr-kosit/validator-configuration-xrechnung) gemeint oder irgend ein internes System. Ich kann das nicht genau einschätzen, da ich nicht so tief in XRechnung drin bin. 

Im Validator selbst gibt es keine "Leitweg-ID".
